osx_image: xcode10.2.1
language: objective-c
xcode_project: MessageDisplayTrain.xcodeproj

stages:
  - build
  - executepy


Build:
  stage: build
  script: xcodebuild -project MessageDisplayTrain.xcodeproj -scheme "MessageDisplayTrain" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'